name: Build NayaGram APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build APK
        run: |
          chmod +x./gradlew
         ./gradlew assembleAfatRelease
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: NayaGram-APK
          path: TMessagesProj_App/build/outputs/apk/afat/release/
